apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: docker-webapp-django
spec:
  environments:
    - name: dev
      authorization:
      - role: RadixAppAdmin
        groups:
        - "g_radix_platform_user"
    - name: prod
      authorization:
      - role: RadixAppAdmin
        groups:
        - "g_radix_platform_user"
  components:
    - name: postgres
      src: ./postgres/
      ports:
       - 5432
      public: false
    - name: app
      src: .
      ports:
       - 8000
      public: false
